### PR TITLE
Project Documentation

### PR DESCRIPTION
**Pull request by danfranc0**
This project is described as a plugin for the music scrobble database, Maloja. Users who could potentially benefit from this plugin will not necessarily be aware due to the lack of information provided. Provided are some suggestions on organizing this project to help potential consumers and contributers.

### CODE REVIEW

**Comment by ICTman1076** [comment]
You do not deserve any rewards from Hacktoberfest for this. I'm disappointed you would use such an event for personal gain without even trying to give back in a valuable way.

**Comment by ICTman1076** [comment]
Apologies, I should've checked more closely - I don't think your PR is related to Hacktoberfest, so ignore that bit.

The sentiment still stands. Your PR is not helpful - projects know they should add this information (where relevant). If you want to be the one to add it, feel free. But don't make PRs telling projects what they "should" be doing - especially when most of it is not actually relevant to the project.

**Comment by danfranc0** [comment]
‎

**Comment by danfranc0** [comment]
Hello,
I am sorry my PR was not helpful to you in any way but you are right. This
was simply an assignment for a class and I was hoping it would be ignored
and I intended to delete once I received my credit. I will make sure to
make meaningful contributions next time I make a documentation-only PR
request. Sorry for wasting your time.
That said your response came off a bit rude and I hope you will keep your
tone more professional in future situations. Maybe I should add that in the
next PR request👍 <https://emojipedia.org/thumbs-up> I appreciate the
feedback though.

**Pull request closed without merging**
